name: Tests
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  ftests:
    name: Functional Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm i
      - name: Run tests
        run: npx jest
